{% set name = "pennylane" %}
{% set version = "0.40.0" %}
{% set build_num = 0 %}

package:
  name: pennylane-suite
  version: {{ version }}

source:
  - url: https://github.com/PennyLaneAI/pennylane/archive/refs/tags/v{{ version }}.tar.gz
    sha256: d7ea41f894de0a7236915f132b57b61b708aa8e4f3c4de0ff1185398cc7beb48
    folder: pennylane
  - url: https://github.com/PennyLaneAI/pennylane-lightning/archive/refs/tags/v{{ version }}.tar.gz
    sha256: a92d118f7256b5440b7d790eef177695a1a7d210cf676e4f64f8abf8f0e65508
    folder: pennylane-lightning

build:
  number: {{ build_num }}
  skip: true  # [py==38]

requirements:
  host:
    - pip
    - python

outputs:
  - name: pennylane-core
    version: {{ version }}
    build:
      number: {{ build_num }}
      skip: true  # [win]
      run_exports:
        - {{ pin_subpackage('pennylane-core', max_pin='x.x.x') }}
      entry_points:
        - pl-device-test=pennylane.devices.tests:cli
      script:
        - cd "${SRC_DIR}/pennylane"
        - {{ PYTHON }} -m pip install . --no-deps -vv
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - pip
        - python
      run:
        - appdirs
        - autograd
        - autoray >=0.6.11
        - cachetools
        - networkx
        - numpy <2.0
        - packaging
        - python
        - requests
        - rustworkx
        - scipy
        - semantic_version >=2.7
        - toml
        - typing_extensions
      run_constrained:
        - pennylane >=0.33
    test:
      imports:
        - pennylane
      requires:
        - pip

  - name: pennylane-lightning-core
    version: {{ version }}
    build:
      number: {{ build_num }}
      skip: true  # [win]
      run_exports:
        - {{ pin_subpackage('pennylane-lightning-core', max_pin='x.x.x') }}
      script:
        - cd "${SRC_DIR}/pennylane-lightning"
        - CMAKE_ARGS="-DENABLE_BLAS=ON -DENABLE_OPENMP=ON -DCMAKE_CXX_COMPILER_TARGET=arm64-apple-macos11 -DCMAKE_SYSTEM_NAME=Darwin -DCMAKE_SYSTEM_PROCESSOR=ARM64" {{ PYTHON }} -m pip install . --no-deps -vv  # [osx and build_platform != target_platform]
        - {{ PYTHON }} setup.py build_ext --define="ENABLE_BLAS=ON;ENABLE_OPENMP=ON"  # [not osx or build_platform == target_platform]
        - {{ PYTHON }} setup.py bdist_wheel  # [not osx or build_platform == target_platform]
        - {{ PYTHON }} -m pip install . --no-deps -vv  # [not osx or build_platform == target_platform]

    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib("c") }}
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - pybind11                               # [build_platform != target_platform]
        # Needed for Windows
        - cmake
        - ninja
        - make
      host:
        - libcblas
        - libgomp               # [linux]
        - llvm-openmp >=16.0.3  # [osx]
        - pip
        - pybind11
        - python
        - setuptools
        - ninja
      run:
        - {{ pin_subpackage('pennylane-core') }}
      run_constrained:
        - pennylane-lightning <0.0a0
    test:
      imports:
        - pennylane_lightning
        - pennylane_lightning.lightning_qubit
        - pennylane_lightning.lightning_qubit_ops  # [build_platform == target_platform]
      requires:
        - pip

  - name: pennylane
    version: {{ version }}
    build:
      number: {{ build_num }}
      skip: true  # [win]
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('pennylane-core', max_pin="x.x.x") }}
        - {{ pin_subpackage('pennylane-lightning-core', max_pin="x.x.x") }}
    test:
      imports:
        - pennylane
        - pennylane_lightning
        - pennylane_lightning.lightning_qubit
        - pennylane_lightning.lightning_qubit_ops  # [build_platform == target_platform]
      commands:
        - pypy --version 2> /dev/null || echo Using Python to run tests
        - pypy -c "import pennylane as qml; qml.about()" 2> /dev/null || echo PyPy not found
        - python -c "import pennylane as qml; qml.about()"
        - pip check
        - pl-device-test --help
        - pl-device-test --device lightning.qubit --shots None --skip-ops  # [build_platform == target_platform]
        - pl-device-test --device lightning.qubit --shots 100000 --skip-ops  # [build_platform == target_platform]
      requires:
        - flaky
        - pip
        - pytest <8.1
        - pytest-benchmark
        - pytest-mock

about:
  home: https://github.com/PennyLaneAI/pennylane
  summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
  license: Apache-2.0 AND MIT
  # MIT is pennylane/grouping/graph_colouring.py
  license_file: pennylane/LICENSE
  doc_url: https://pennylane.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - BastianZim
    - leofang
    - maliasadi
    - vincentmr
  feedstock-name: pennylane
